/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pois: Pois;
    sessions: Session;
    rewards: Reward;
    challenges: Challenge;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pois: PoisSelect<false> | PoisSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    rewards: RewardsSelect<false> | RewardsSelect<true>;
    challenges: ChallengesSelect<false> | ChallengesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'challenge-config': ChallengeConfig;
    'game-config': GameConfig;
    mail: Mail;
  };
  globalsSelect: {
    'challenge-config': ChallengeConfigSelect<false> | ChallengeConfigSelect<true>;
    'game-config': GameConfigSelect<false> | GameConfigSelect<true>;
    mail: MailSelect<false> | MailSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Unique username for the user
   */
  username: string;
  /**
   * Whether the user has premium subscription
   */
  isPremium?: boolean | null;
  /**
   * Total seconds earned from all claims
   */
  totalSeconds?: number | null;
  /**
   * Total number of unique POIs claimed
   */
  totalPOIsClaimed?: number | null;
  /**
   * Number of POIs where user is currently the king
   */
  currentKingOf?: number | null;
  /**
   * Longest streak of consecutive days with claims
   */
  longestStreak?: number | null;
  /**
   * Current streak of consecutive days with claims
   */
  currentStreak?: number | null;
  /**
   * Last time user was active
   */
  lastActive?: string | null;
  /**
   * User home country
   */
  homeCountry?: string | null;
  /**
   * User home city
   */
  homeCity?: string | null;
  /**
   * Home city latitude
   */
  homeCityLat?: number | null;
  /**
   * Home city longitude
   */
  homeCityLng?: number | null;
  /**
   * When location was last updated
   */
  locationUpdatedAt?: string | null;
  /**
   * Number of times location has been updated
   */
  locationUpdateCount?: number | null;
  /**
   * User coins for purchasing challenge buyouts
   */
  coins?: number | null;
  /**
   * User notification preferences
   */
  notificationSettings?: {
    poiNearby?: boolean | null;
    captureComplete?: boolean | null;
    kingStatusChanged?: boolean | null;
    newChallenge?: boolean | null;
    friendActivity?: boolean | null;
    leaderboardUpdate?: boolean | null;
    dailyReminder?: boolean | null;
    weeklyReport?: boolean | null;
  };
  /**
   * Push tokens for this user (supports multiple devices)
   */
  pushTokens?:
    | {
        /**
         * Expo push token
         */
        expoPushToken: string;
        /**
         * Platform of the device
         */
        platform?: ('ios' | 'android') | null;
        /**
         * Device identifier
         */
        deviceId?: string | null;
        /**
         * Whether this token is active
         */
        isActive?: boolean | null;
        /**
         * When this token was last updated
         */
        updatedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * User role
   */
  role: 'user' | 'admin';
  /**
   * Active rewards for this user
   */
  activeRewards?:
    | {
        /**
         * The reward that is active
         */
        reward: string | Reward;
        /**
         * Denormalized reward type for speed
         */
        rewardType: string;
        /**
         * Denormalized reward value for speed
         */
        rewardValue: number;
        /**
         * When the reward was activated
         */
        activatedAt?: string | null;
        /**
         * Duration in hours (null for unlimited/season-based)
         */
        duration?: number | null;
        /**
         * YYYY-MM format, for season-based rewards like bonus_crowns
         */
        season?: string | null;
        /**
         * For use-based rewards, number of uses remaining (null for unlimited or season-based)
         */
        usesRemaining?: number | null;
        /**
         * Whether this reward is currently active
         */
        isActive?: boolean | null;
        /**
         * ID of the challenge that granted this reward
         */
        challengeId?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rewards".
 */
export interface Reward {
  id: string;
  /**
   * Type of reward
   */
  rewardType:
    | 'entry_time_reduction'
    | 'bonus_seconds'
    | 'larger_radius'
    | 'extended_capture'
    | 'bonus_crowns'
    | 'decay_reduction'
    | 'coins';
  /**
   * Reward value (e.g., 0.1 for 10% reduction, 10 for bonus seconds)
   */
  rewardValue: number;
  /**
   * Duration in hours (null for session-based or season-based)
   */
  rewardDuration?: number | null;
  /**
   * Number of times to use (null for unlimited or season-based)
   */
  rewardUses?: number | null;
  /**
   * Difficulty level (1-9)
   */
  difficulty: number;
  /**
   * Description of the reward
   */
  description: string;
  /**
   * Whether this reward is active
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pois".
 */
export interface Pois {
  /**
   * Unique identifier for the POI (e.g., OSM ID)
   */
  id: string;
  /**
   * Name of the POI
   */
  name: string;
  /**
   * Geographic coordinates (longitude, latitude)
   *
   * @minItems 2
   * @maxItems 2
   */
  coordinates: [number, number];
  /**
   * Latitude (for easier querying)
   */
  latitude: number;
  /**
   * Longitude (for easier querying)
   */
  longitude: number;
  /**
   * POI type (e.g., park, church, monument)
   */
  type: string;
  /**
   * POI category (e.g., leisure, religion, tourism)
   */
  category: string;
  /**
   * User who currently has the most seconds at this POI
   */
  currentKing?: (string | null) | User;
  /**
   * City name where the POI is located
   */
  city?: string | null;
  /**
   * Country name where the POI is located
   */
  country?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: string;
  /**
   * User who made this session
   */
  user: string | User;
  /**
   * POI where the session took place
   */
  poi: string | Pois;
  /**
   * When the session started
   */
  startTime: string;
  /**
   * When the session ended
   */
  endTime?: string | null;
  /**
   * Seconds earned from this session
   */
  secondsEarned: number;
  /**
   * Month in YYYY-MM format for leaderboard grouping
   */
  month: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenges".
 */
export interface Challenge {
  id: string;
  /**
   * User who has this challenge
   */
  user: string | User;
  /**
   * Challenge type
   */
  type: 'daily' | 'weekly' | 'monthly';
  /**
   * Challenge title
   */
  title: string;
  /**
   * Challenge description
   */
  description: string;
  /**
   * Type of challenge objective
   */
  challengeType:
    | 'entry_count'
    | 'crown_claim'
    | 'session_duration'
    | 'longest_session'
    | 'unique_pois'
    | 'category_variety'
    | 'category_similarity'
    | 'new_location';
  /**
   * Target value (e.g., 5 entries, 3 crowns)
   */
  targetValue: number;
  /**
   * Optional: Target category (e.g., park, church)
   */
  targetCategory?: string | null;
  /**
   * Difficulty level (1-9) that determines which reward is assigned
   */
  rewardDifficulty: number;
  /**
   * Number of coins to buy out challenge (0 means not purchasable)
   */
  cost?: number | null;
  /**
   * The assigned reward for this challenge (optional - coin challenges give coins directly)
   */
  reward?: (string | null) | Reward;
  /**
   * Current progress towards the challenge
   */
  progress?: number | null;
  /**
   * When the challenge was completed
   */
  completedAt?: string | null;
  /**
   * When the challenge expires (for daily/weekly/monthly)
   */
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pois';
        value: string | Pois;
      } | null)
    | ({
        relationTo: 'sessions';
        value: string | Session;
      } | null)
    | ({
        relationTo: 'rewards';
        value: string | Reward;
      } | null)
    | ({
        relationTo: 'challenges';
        value: string | Challenge;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  username?: T;
  isPremium?: T;
  totalSeconds?: T;
  totalPOIsClaimed?: T;
  currentKingOf?: T;
  longestStreak?: T;
  currentStreak?: T;
  lastActive?: T;
  homeCountry?: T;
  homeCity?: T;
  homeCityLat?: T;
  homeCityLng?: T;
  locationUpdatedAt?: T;
  locationUpdateCount?: T;
  coins?: T;
  notificationSettings?:
    | T
    | {
        poiNearby?: T;
        captureComplete?: T;
        kingStatusChanged?: T;
        newChallenge?: T;
        friendActivity?: T;
        leaderboardUpdate?: T;
        dailyReminder?: T;
        weeklyReport?: T;
      };
  pushTokens?:
    | T
    | {
        expoPushToken?: T;
        platform?: T;
        deviceId?: T;
        isActive?: T;
        updatedAt?: T;
        id?: T;
      };
  role?: T;
  activeRewards?:
    | T
    | {
        reward?: T;
        rewardType?: T;
        rewardValue?: T;
        activatedAt?: T;
        duration?: T;
        season?: T;
        usesRemaining?: T;
        isActive?: T;
        challengeId?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pois_select".
 */
export interface PoisSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  coordinates?: T;
  latitude?: T;
  longitude?: T;
  type?: T;
  category?: T;
  currentKing?: T;
  city?: T;
  country?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  user?: T;
  poi?: T;
  startTime?: T;
  endTime?: T;
  secondsEarned?: T;
  month?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rewards_select".
 */
export interface RewardsSelect<T extends boolean = true> {
  rewardType?: T;
  rewardValue?: T;
  rewardDuration?: T;
  rewardUses?: T;
  difficulty?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenges_select".
 */
export interface ChallengesSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  title?: T;
  description?: T;
  challengeType?: T;
  targetValue?: T;
  targetCategory?: T;
  rewardDifficulty?: T;
  cost?: T;
  reward?: T;
  progress?: T;
  completedAt?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge-config".
 */
export interface ChallengeConfig {
  id: string;
  /**
   * Number of daily challenges to generate per user
   */
  dailyChallengesCount: number;
  /**
   * Number of weekly challenges to generate for all users
   */
  weeklyChallengesCount: number;
  /**
   * Number of monthly challenges to generate for all users
   */
  monthlyChallengesCount: number;
  dailyEntryCount: {
    /**
     * Easy: target value (e.g., 1 entry)
     */
    easy: number;
    /**
     * Medium: target value (e.g., 1 entry)
     */
    medium: number;
    /**
     * Hard: target value (e.g., 2 entries)
     */
    hard: number;
  };
  dailyCrownClaim: {
    easy: number;
    medium: number;
    hard: number;
  };
  dailySessionDuration: {
    /**
     * Easy: target value in seconds (e.g., 900 = 15 minutes)
     */
    easy: number;
    /**
     * Medium: target value in seconds (e.g., 1800 = 30 minutes)
     */
    medium: number;
    /**
     * Hard: target value in seconds (e.g., 3600 = 60 minutes)
     */
    hard: number;
  };
  dailyLongestSession: {
    /**
     * Easy: target value in seconds (e.g., 300 = 5 minutes)
     */
    easy: number;
    /**
     * Medium: target value in seconds (e.g., 600 = 10 minutes)
     */
    medium: number;
    /**
     * Hard: target value in seconds (e.g., 900 = 15 minutes). Maximum 60 minutes for daily challenges.
     */
    hard: number;
  };
  dailyUniquePois: {
    easy: number;
    medium: number;
    hard: number;
  };
  dailyCategoryVariety: {
    easy: number;
    medium: number;
    hard: number;
  };
  dailyCategorySimilarity: {
    /**
     * Easy: target value (e.g., 1 session at same category)
     */
    easy: number;
    /**
     * Medium: target value (e.g., 2 sessions at same category)
     */
    medium: number;
    /**
     * Hard: target value (e.g., 3 sessions at same category)
     */
    hard: number;
  };
  dailyNewLocation: {
    easy: number;
    medium: number;
    hard: number;
  };
  weeklyEntryCount: {
    easy: number;
    medium: number;
    hard: number;
  };
  weeklyCrownClaim: {
    easy: number;
    medium: number;
    hard: number;
  };
  weeklySessionDuration: {
    /**
     * Easy: target value in seconds (e.g., 5400 = 90 minutes)
     */
    easy: number;
    /**
     * Medium: target value in seconds (e.g., 10800 = 180 minutes)
     */
    medium: number;
    /**
     * Hard: target value in seconds (e.g., 21600 = 360 minutes)
     */
    hard: number;
  };
  weeklyLongestSession: {
    /**
     * Easy: target value in seconds (e.g., 600 = 10 minutes)
     */
    easy: number;
    /**
     * Medium: target value in seconds (e.g., 1200 = 20 minutes)
     */
    medium: number;
    /**
     * Hard: target value in seconds (e.g., 1800 = 30 minutes). Maximum 60 minutes.
     */
    hard: number;
  };
  weeklyUniquePois: {
    easy: number;
    medium: number;
    hard: number;
  };
  weeklyCategoryVariety: {
    easy: number;
    medium: number;
    hard: number;
  };
  weeklyCategorySimilarity: {
    /**
     * Easy: target value (e.g., 3 sessions at same category)
     */
    easy: number;
    /**
     * Medium: target value (e.g., 5 sessions at same category)
     */
    medium: number;
    /**
     * Hard: target value (e.g., 7 sessions at same category)
     */
    hard: number;
  };
  weeklyNewLocation: {
    easy: number;
    medium: number;
    hard: number;
  };
  monthlyEntryCount: {
    easy: number;
    medium: number;
    hard: number;
  };
  monthlyCrownClaim: {
    easy: number;
    medium: number;
    hard: number;
  };
  monthlySessionDuration: {
    /**
     * Easy: target value in seconds (e.g., 21600 = 360 minutes)
     */
    easy: number;
    /**
     * Medium: target value in seconds (e.g., 43200 = 720 minutes)
     */
    medium: number;
    /**
     * Hard: target value in seconds (e.g., 86400 = 1440 minutes)
     */
    hard: number;
  };
  monthlyLongestSession: {
    /**
     * Easy: target value in seconds (e.g., 1200 = 20 minutes). Maximum 60 minutes.
     */
    easy: number;
    /**
     * Medium: target value in seconds (e.g., 2400 = 40 minutes). Maximum 60 minutes.
     */
    medium: number;
    /**
     * Hard: target value in seconds (e.g., 3600 = 60 minutes). Maximum 60 minutes.
     */
    hard: number;
  };
  monthlyUniquePois: {
    easy: number;
    medium: number;
    hard: number;
  };
  monthlyCategoryVariety: {
    easy: number;
    medium: number;
    hard: number;
  };
  monthlyCategorySimilarity: {
    /**
     * Easy: target value (e.g., 8 sessions at same category)
     */
    easy: number;
    /**
     * Medium: target value (e.g., 12 sessions at same category)
     */
    medium: number;
    /**
     * Hard: target value (e.g., 20 sessions at same category)
     */
    hard: number;
  };
  monthlyNewLocation: {
    easy: number;
    medium: number;
    hard: number;
  };
  titleTemplates: {
    /**
     * Template for entry count challenges. Use {targetValue}, {period}, {category} as placeholders
     */
    entryCount: string;
    /**
     * Template for crown claim challenges
     */
    crownClaim: string;
    /**
     * Template for crown takeover challenges
     */
    crownTakeover: string;
    /**
     * Template for session duration challenges
     */
    sessionDuration: string;
    /**
     * Template for longest session challenges
     */
    longestSession: string;
    /**
     * Template for unique POIs challenges
     */
    uniquePois: string;
    /**
     * Template for category variety challenges
     */
    categoryVariety: string;
    /**
     * Template for category similarity challenges
     */
    categorySimilarity: string;
    /**
     * Template for new location challenges
     */
    newLocation: string;
  };
  descriptionTemplates: {
    /**
     * Template for entry count challenge descriptions
     */
    entryCount: string;
    crownClaim: string;
    crownTakeover: string;
    sessionDuration: string;
    longestSession: string;
    uniquePois: string;
    categoryVariety: string;
    categorySimilarity: string;
    newLocation: string;
  };
  costMultipliers: {
    /**
     * Base cost multiplier for easy challenges
     */
    easy: number;
    /**
     * Base cost multiplier for medium challenges
     */
    medium: number;
    /**
     * Base cost multiplier for hard challenges
     */
    hard: number;
  };
  availableCategories?:
    | {
        category: string;
        /**
         * Difficulty adjustment for category-specific challenges (+1, +2, etc.)
         */
        difficultyAdjustment?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Core game mechanics and balance configuration
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-config".
 */
export interface GameConfig {
  id: string;
  /**
   * Maximum seconds a user can earn per POI per day
   */
  dailySecondsLimit: number;
  /**
   * Entry mode duration in seconds (before capture starts for normal users)
   */
  entryDuration: number;
  /**
   * Entry mode duration in seconds for POI kings (reduced time)
   */
  kingEntryDuration: number;
  /**
   * Detection radius around POI in meters
   */
  poiRadius: number;
  /**
   * Maximum seconds per capture session
   */
  maxCaptureSeconds: number;
  /**
   * Bonus seconds awarded for completing a full minute (60s + bonus = total)
   */
  minuteBonusSeconds: number;
  /**
   * Default daily decay percentage applied to user totalSeconds
   */
  defaultDecayPercentage: number;
  /**
   * Maximum decay reduction percentage (minimum decay = default - max)
   */
  maxDecayReduction: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mail".
 */
export interface Mail {
  id: string;
  fromEmail: string;
  fromName: string;
  verify?: {
    /**
     * Use the following placeholders to insert dynamic values: {{name}}, {{verifyLink}}
     */
    subject?: string | null;
    /**
     * Use the following placeholders to insert dynamic values: {{name}}, {{verifyLink}}
     */
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  forgotPassword?: {
    /**
     * Use the following placeholders to insert dynamic values: {{token}}, {{origin}}
     */
    subject?: string | null;
    /**
     * Use the following placeholders to insert dynamic values: {{token}}, {{origin}}
     */
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "challenge-config_select".
 */
export interface ChallengeConfigSelect<T extends boolean = true> {
  dailyChallengesCount?: T;
  weeklyChallengesCount?: T;
  monthlyChallengesCount?: T;
  dailyEntryCount?:
    | T
    | {
        easy?: T;
        medium?: T;
        hard?: T;
      };
  dailyCrownClaim?:
    | T
    | {
        easy?: T;
        medium?: T;
        hard?: T;
      };
  dailySessionDuration?:
    | T
    | {
        easy?: T;
        medium?: T;
        hard?: T;
      };
  dailyLongestSession?:
    | T
    | {
        easy?: T;
        medium?: T;
        hard?: T;
      };
  dailyUniquePois?:
    | T
    | {
        easy?: T;
        medium?: T;
        hard?: T;
      };
  dailyCategoryVariety?:
    | T
    | {
        easy?: T;
        medium?: T;
        hard?: T;
      };
  dailyCategorySimilarity?:
    | T
    | {
        easy?: T;
        medium?: T;
        hard?: T;
      };
  dailyNewLocation?:
    | T
    | {
        easy?: T;
        medium?: T;
        hard?: T;
      };
  weeklyEntryCount?:
    | T
    | {
        easy?: T;
        medium?: T;
        hard?: T;
      };
  weeklyCrownClaim?:
    | T
    | {
        easy?: T;
        medium?: T;
        hard?: T;
      };
  weeklySessionDuration?:
    | T
    | {
        easy?: T;
        medium?: T;
        hard?: T;
      };
  weeklyLongestSession?:
    | T
    | {
        easy?: T;
        medium?: T;
        hard?: T;
      };
  weeklyUniquePois?:
    | T
    | {
        easy?: T;
        medium?: T;
        hard?: T;
      };
  weeklyCategoryVariety?:
    | T
    | {
        easy?: T;
        medium?: T;
        hard?: T;
      };
  weeklyCategorySimilarity?:
    | T
    | {
        easy?: T;
        medium?: T;
        hard?: T;
      };
  weeklyNewLocation?:
    | T
    | {
        easy?: T;
        medium?: T;
        hard?: T;
      };
  monthlyEntryCount?:
    | T
    | {
        easy?: T;
        medium?: T;
        hard?: T;
      };
  monthlyCrownClaim?:
    | T
    | {
        easy?: T;
        medium?: T;
        hard?: T;
      };
  monthlySessionDuration?:
    | T
    | {
        easy?: T;
        medium?: T;
        hard?: T;
      };
  monthlyLongestSession?:
    | T
    | {
        easy?: T;
        medium?: T;
        hard?: T;
      };
  monthlyUniquePois?:
    | T
    | {
        easy?: T;
        medium?: T;
        hard?: T;
      };
  monthlyCategoryVariety?:
    | T
    | {
        easy?: T;
        medium?: T;
        hard?: T;
      };
  monthlyCategorySimilarity?:
    | T
    | {
        easy?: T;
        medium?: T;
        hard?: T;
      };
  monthlyNewLocation?:
    | T
    | {
        easy?: T;
        medium?: T;
        hard?: T;
      };
  titleTemplates?:
    | T
    | {
        entryCount?: T;
        crownClaim?: T;
        crownTakeover?: T;
        sessionDuration?: T;
        longestSession?: T;
        uniquePois?: T;
        categoryVariety?: T;
        categorySimilarity?: T;
        newLocation?: T;
      };
  descriptionTemplates?:
    | T
    | {
        entryCount?: T;
        crownClaim?: T;
        crownTakeover?: T;
        sessionDuration?: T;
        longestSession?: T;
        uniquePois?: T;
        categoryVariety?: T;
        categorySimilarity?: T;
        newLocation?: T;
      };
  costMultipliers?:
    | T
    | {
        easy?: T;
        medium?: T;
        hard?: T;
      };
  availableCategories?:
    | T
    | {
        category?: T;
        difficultyAdjustment?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-config_select".
 */
export interface GameConfigSelect<T extends boolean = true> {
  dailySecondsLimit?: T;
  entryDuration?: T;
  kingEntryDuration?: T;
  poiRadius?: T;
  maxCaptureSeconds?: T;
  minuteBonusSeconds?: T;
  defaultDecayPercentage?: T;
  maxDecayReduction?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mail_select".
 */
export interface MailSelect<T extends boolean = true> {
  fromEmail?: T;
  fromName?: T;
  verify?:
    | T
    | {
        subject?: T;
        content?: T;
      };
  forgotPassword?:
    | T
    | {
        subject?: T;
        content?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}